/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Bean.HoKhauBean;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import services.MysqlConnection;
/**
 *
 * @author CONG_CHINH
 */
public class Lich_Hop extends javax.swing.JFrame {

    /**
     * Creates new form Lich_Hop
     */
    public Lich_Hop() {
        initComponents();
         try {
            loadidSuKien();
            sukien();
        } catch (SQLException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        }
        load();
    }
     public void load(){
        try { 
            Connection conn =  MysqlConnection.getMysqlConnection();
            String sql = "SELECT `id`,`chuDe`,`suKien`,`thoiGian`,`ngayHop`, `diaDiem` FROM `lich_hop` ";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                String ID = String.valueOf(rs.getInt("id"));
                String chuDe= rs.getString("chuDe");
                String suKien= rs.getString("suKien");
                String thoiGian = rs.getString("thoiGian");
                String ngayHop = rs.getString("ngayHop");
                String diaDiem = rs.getString("diaDiem");
                String tbData[] = {ID, chuDe,suKien,thoiGian, ngayHop,diaDiem};
                DefaultTableModel tblModel = (DefaultTableModel)tbList1.getModel();
                tblModel.addRow(tbData);              
                
                
            tbList1.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void loadidSuKien() throws SQLException, ClassNotFoundException{
    try {
        Connection conn = MysqlConnection.getMysqlConnection();
    String sql = "SELECT id FROM lich_hop";
    PreparedStatement pr = conn.prepareStatement(sql);
    ResultSet rs = pr.executeQuery();
        while(rs.next()){
            idchude.addItem(rs.getString(1));
            
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}


public void sukien  () throws SQLException, ClassNotFoundException{
    try {
        Connection conn = MysqlConnection.getMysqlConnection();
    String sql = "SELECT suKien FROM su_kien";
        PreparedStatement pr = conn.prepareStatement(sql);
        ResultSet rs = pr.executeQuery();
        while(rs.next()){
            sukien.addItem(rs.getString(1));
            
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbList1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtchude = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdiadiem = new javax.swing.JTextField();
        txtthoigian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sukien = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        idchude = new javax.swing.JComboBox<>();
        txtngayhop = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbList1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Chủ Đề", "Sự Kiện", "Ngày Họp", "Thời Gian Diễn Ra", "Địa Điểm Tổ Chức"
            }
        ));
        jScrollPane1.setViewportView(tbList1);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        del.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+1));
        jLabel1.setText("Chủ Đề:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Ngày Họp:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Thời Gian Diễn Ra");

        txtchude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchudeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Địa Điểm Tổ Chức");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+1));
        jLabel5.setText("Sự Kiện:");

        sukien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukienActionPerformed(evt);
            }
        });

        jLabel6.setText("Select ID");

        idchude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idchudeActionPerformed(evt);
            }
        });

        txtngayhop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayhopActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Xem");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiadiem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngayhop, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtchude, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5))
                                        .addGap(38, 38, 38)
                                        .addComponent(sukien, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idchude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sukien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtchude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtngayhop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtthoigian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(idchude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiadiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(2, 2, 2)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(del))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
           
            String chude = txtchude.getText();
            String sukien = this.sukien.getSelectedItem().toString();
            String thoigian = txtthoigian.getText();
//            Date ngayhop = ngayHopDc.getDate();
            String ngayhop = txtngayhop.getText();
            String diadiem = txtdiadiem.getText();
           
            String query = "INSERT INTO `lich_hop` (`chuDe`,`suKien`, `thoiGian`, `ngayHop`, `diaDiem`) values (?,?,?,?,?)";
            Connection conn = MysqlConnection.getMysqlConnection();

            PreparedStatement pr = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            ResultSet rs = pr.getGeneratedKeys();
            pr.setString(1, chude);
            pr.setString(2, sukien);
            pr.setString(3, thoigian);
//            java.sql.Date tuNgay = new java.sql.Date(ngayhop.getTime());
//            pr.setDate(4, (java.sql.Date) ngayhop);
            pr.setString(4, ngayhop);
            pr.setString(5, diadiem);
            int k = pr.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Tạo lịch họp thành công !");
                txtchude.setText("");
                txtthoigian.setText("");
                txtdiadiem.setText("");
                //                txtThuPhi.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        }
        load();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

        try {
            String chude = txtchude.getText();
            String sukien = this.sukien.getSelectedItem().toString();
            String thoigian = txtthoigian.getText();
//            Date ngayhop = ngayHopDc.getDate();
            String ngayhop = txtngayhop.getText();
            String diadiem = txtdiadiem.getText();
            String id = idchude.getSelectedItem().toString();
            String query = "UPDATE  `lich_hop` set chuDe = ? ,  suKien = ? ,`thoiGian`=?, `ngayHop` = ?, `diaDiem` = ? where id =? ";
            Connection conn = MysqlConnection.getMysqlConnection();

            PreparedStatement pr = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            System.out.println(pr);
            ResultSet rs = pr.getGeneratedKeys();
            pr.setString(1, chude);
            pr.setString(2, sukien);
            pr.setString(3, thoigian);
//            pr.setDate(4, (java.sql.Date) ngayhop);
            pr.setString(4, ngayhop);
            pr.setString(5, diadiem);
            pr.setString(6, id);
            System.out.println(pr);
            int k = pr.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Cập nhật lịch họp thành công");
                txtchude.setText("");
                txtthoigian.setText("");
                txtdiadiem.setText("");
                //                txtThuPhi.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        }
        load();
    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        try {

            String id = idchude.getSelectedItem().toString();
            String query = "DELETE FROM `lich_hop` WHERE id = ? ";
            Connection conn = MysqlConnection.getMysqlConnection();

            PreparedStatement pr = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            ResultSet rs = pr.getGeneratedKeys();

            pr.setString(1, id);
            int k = pr.executeUpdate();
            if (k==1){
                JOptionPane.showMessageDialog(this, "Delete successfully");
                //                txtThuPhi.setText("");
            }else{
                JOptionPane.showMessageDialog(this, "nno");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Lich_Hop.class.getName()).log(Level.SEVERE, null, ex);
        }
        load();
    }//GEN-LAST:event_delActionPerformed

    private void txtchudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchudeActionPerformed

    private void sukienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sukienActionPerformed

    private void idchudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idchudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idchudeActionPerformed

    private void txtngayhopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayhopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngayhopActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        load();
    }//GEN-LAST:event_jButton4ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lich_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lich_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lich_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lich_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lich_Hop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JComboBox<String> idchude;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sukien;
    private javax.swing.JTable tbList1;
    private javax.swing.JTextField txtchude;
    private javax.swing.JTextField txtdiadiem;
    private javax.swing.JTextField txtngayhop;
    private javax.swing.JTextField txtthoigian;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
